[workspace]
members = [
    "wingspan",
    "wingspan-buffer",
]

[patch.crates-io]
druid = { git = "https://github.com/adotinthevoid/druid/", branch = "public-test-hack" }
ropey = { git = "https://github.com/aDotInTheVoid/ropey/", branch = "omicoron" }
