[workspace]
members = [
    "wingspan",
    "wingspan-buffer",
]

[patch.crates-io]
druid = { git = "https://github.com/linebender/druid", rev = "1e28dcf" }
ropey = { git = "https://github.com/aDotInTheVoid/ropey/", branch = "omicoron" }
