[package]
name = "textarea"
version = "0.1.0"
authors = ["Nixon Enraght-Moony <nixon.emoony@gmail.com>"]
edition = "2018"
license = "Apache-2.0"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.6.0"
textedit = {path = "../textedit", features=["druid"]}
color-eyre = "0.5"

[dependencies.ropey]
git = "https://github.com/aDotInTheVoid/ropey/"
rev =  "653048c"

